### PR TITLE
More style changes

### PR DESCRIPTION
**Pull request by savitakartik**

### CODE REVIEW

**Comment by savitakartik** [comment]
https://github.com/tskit-dev/tsqc/assets/25925005/3262b34e-738e-4161-b42f-21e1f5d3e203

**Comment by savitakartik** [comment]
Need to figure out how to set colours globally and clean up duplicated code, but just wanted to get feedback on style.

**Comment by jeromekelleher** [comment]
Styling looks great!

**Comment by jeromekelleher** [comment]
The Pr needs a rebase (I think, just dropping the first two commits)

**Pull request merged**
