### PR TITLE
API for PNG creation of pages

### PR DESCRIPTION
**Pull request by benjeffery**
Here's a quick stab at what it would look like to have an API for making PNGs of pages, addressing #158
Output looks like:
mutations_scatter

### CODE REVIEW

**Comment by jeromekelleher** [comment]
That's very neat, we want this!

Are you excluding interactive elements because there's an issue or to avoid cluttering up visuals?

**Comment by benjeffery** [comment]
I'm excluding them just to make more space for the plot, it works if you leave them in.

**Comment by savitakartik** [comment]
This is amazing! Did you need to install selenium, Ben?

**Comment by jeromekelleher** [comment]
Ah right - let's keep it as simple as possible for now so, as there's a big refactor in the pipeline, and the layout of these pages will change. We can tweak which elements are visible for non interactive when that settles.

**Comment by benjeffery** [comment]
> This is amazing! Did you need to install selenium, Ben?

Yes, but it's just a quick `pip install`.

**Comment by benjeffery** [comment]
> Ah right - let's keep it as simple as possible for now so, as there's a big refactor in the pipeline, and the layout of these pages will change. We can tweak which elements are visible for non interactive when that settles.

Yes, makes sense, I was exploring what was possible, but this PR should just be the raster infrastructure with no page changes. 

I think this could also be useful for PRs that change the pages - would get a live preview of the new content.

**Comment by benjeffery** [comment]
Ready for review, this is just the core API, follow up at #161.

**Review by jeromekelleher — APPROVED** [review]
Lgtm

**Pull request merged**
