### PR TITLE
Rejig main entry point

### LINKED ISSUE #82: support tszipped files as input
Nice to support tszip files also when provided as input.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Change how we run tsqc from using ``panel serve`` to ``python3 main.py``. This is a step towards packaging everything up in a more standard way, where we ship this as a Python package.

Also clarifies the logic of when we load up the datafile and how we cache it, which was quite confusing before.

Also supports tszip input.

Closes #82

### CODE REVIEW

**Review by savitakartik — APPROVED** [review]

**Comment by savitakartik** [comment]
Looks great!

**Comment by savitakartik** [comment]
Oe small note - in WSL, previously VSCode would prompt me to open the app in a browser but now I get these messages:
image
Adding `BROWSER=/path/to/browser.exe` to the path fixed it.

**Comment by savitakartik** [comment]
I had 2 questions related to this PR:
> now that tzipped files are supported, would it make sense to add a test to check pages are loaded correctly when a compressed file is provided?
> is it a good idea to add a `--help` option to the `click` interface?

**Comment by jeromekelleher** [comment]
Thanks for taking a look @savitakartik, this is very helpful. We'll need to fix/document the behaviour in WSL. 

I've added #89 to track adding tests for compressed input

There should already be a help interface:
```
$ python3 main.py --help
Usage: main.py [OPTIONS] PATH

  Run the tsqc server.

Options:
  --port INTEGER  Port to serve on
  --help          Show this message and exit.
```
it's pretty basic, but we can fill it out as we go. Does this work for you?

**Review by benjeffery — APPROVED** [review]
LGTM. Seems to remove the ability to use `--dev` as I can't see any option on `panel.serve` which does that, but I can live with that.

**Comment by savitakartik** [comment]
> Thanks for taking a look @savitakartik, this is very helpful. We'll need to fix/document the behaviour in WSL.
> 
> I've added #89 to track adding tests for compressed input
> 
> There should already be a help interface:
> 
> ```
> $ python3 main.py --help
> Usage: main.py [OPTIONS] PATH
> 
>   Run the tsqc server.
> 
> Options:
>   --port INTEGER  Port to serve on
>   --help          Show this message and exit.
> ```
> 
> it's pretty basic, but we can fill it out as we go. Does this work for you?

Ah, must have missed it, totally works for me!

**Pull request merged**
