### PR TITLE
add edge area histograms

### PR DESCRIPTION
**Pull request by savitakartik**
partial fix for issue #132

### CODE REVIEW

**Comment by savitakartik** [comment]
[

https://github.com/tskit-dev/tsqc/assets/25925005/f380846f-aa81-4c98-969b-7597ff8ee6cd

]

**Comment by jeromekelleher** [comment]
LGTM - shall we merge this much and refine afterwards?

@benjeffery - looks like we have a Dask version problem in the tests. Can you have a look and advise please? It's not clear that we need Dask directly ourselves, but maybe it's getting pulled in my one of the deps.

**Comment by savitakartik** [comment]
Definitely needs to be refined. Ok to merge this much for now, and I'll get back to this after ProbGen.

**Comment by jeromekelleher** [comment]
OK, let's merge this. Hopefully we can resolve the Dask issue at some point @benjeffery?

**Pull request merged**
